[main]
debug = false
timezone = "Europe/Minsk"

[bot]
token = ""
admin-pass = ""
admin-id = []
threads = 4
drop-pending = true

[database]
    [database.connection]
    drivername = 'mysql'
    username = 'shprote_db_user'
    password = 'shprote_db_user_password'
    host = '127.0.0.1'
    port = 3306
    database = 'shprote_db'

    [database.options]
    recycle = 3600
    pre-ping = true

[log]
maxfiles = 5
maxsize = 5_242_880 # 5MB
stdout = true

[ffmpeg]
path = ""
