[main]
debug = false
token = ""
admin-pass = ""
admin-id = []
threads = 4
timezone = "Europe/Minsk"

[database]
    [database.connection]
    drivername = 'driver'
    username = 'username'
    password = 'password'
    host = '127.0.0.1'
    port = 5000
    database = 'mydb'

    [database.options]
    recycle = 3600
    pre-ping = true

[log]
maxfiles = 5
maxsize = 5_242_880 # 5MB
stdout = true
